### ISSUE TITLE
problem with meta class 

### ISSUE THREAD

**Issue by JJ-Author** [AKSW/QuitDiff#7]
following error occurs when running with python 2.7.12

```
/usr/bin/python2.7 /home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/bin/quit-diff . a.ttl 1 2 b.ttl
('.', 'a.ttl', 'b.ttl')
Traceback (most recent call last):
  File "/home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/bin/quit-diff", line 6, in <module>
    quit_diff.main()
  File "/home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/quit_diff/__init__.py", line 26, in main
    quitdiff.diff(args.path, args.oldFile, args.newFile, diffFormat=args.diffFormat)
  File "/home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/quit_diff/QuitDiff.py", line 74, in diff
    self.difftool(oldFile, newFile, None, None, diffFormat=diffFormat)
  File "/home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/quit_diff/QuitDiff.py", line 110, in difftool
    diff = getattr(import_module('quit_diff.serializer.' + module), module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kilt/Desktop/johannes-kilt/students/Denis/QuitDiff/quit_diff/serializer/SparqlDiff.py", line 5
    class SparqlDiff(metaclass=ABCMeta):
                              ^
SyntaxError: invalid syntax
```

**Comment by white-gecko** [comment]
Hello @JJ-Author, as far as I can remember we have developed Quit Diff with Python 3. Please try to execute it with python 3.

**Comment by JJ-Author** [comment]
Yes that works. Maybe add the required version and a quick installation hint in the readme?

**Comment by white-gecko** [comment]
Yes!

**Comment by white-gecko** [comment]
We are also looking forward to your pull requests, if you have any suggestions or if you just take notes of observations you make when installing and using the software.

**Comment by white-gecko** [comment]
The requirements should be more clear in 08b86e530b2c70598d600f286512feb1050b3419 now

**Comment by JJ-Author** [comment]
perfect. current workaround is generating a pre-diff with sort and comm unix utils and then pass over this reduced diff (~300mb) to quitdiff.
